#pragma once
#define CONFIGURATION_H_VERSION 02000801
#define SHOW_BOOTSCREEN
#define SHOW_CUSTOM_BOOTSCREEN
#define CUSTOM_STATUS_SCREEN_IMAGE
#define SERIAL_PORT 2
#define SERIAL_PORT_2 -1
#define BAUDRATE 115200
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2
#endif
#define CUSTOM_MACHINE_NAME "Ender-3"
#define EXTRUDERS 1
#define DEFAULT_NOMINAL_FILAMENT_DIA 1.75
#if ENABLED(SINGLENOZZLE)
#endif
#if ENABLED(SWITCHING_EXTRUDER)
  #define SWITCHING_EXTRUDER_SERVO_NR 0
  #if EXTRUDERS > 3
    #define SWITCHING_EXTRUDER_E23_SERVO_NR 1
  #endif
#endif
#if ENABLED(SWITCHING_NOZZLE)
  #define SWITCHING_NOZZLE_SERVO_NR 0
#endif
#if EITHER(PARKING_EXTRUDER, MAGNETIC_PARKING_EXTRUDER)
  #if ENABLED(PARKING_EXTRUDER)
  #elif ENABLED(MAGNETIC_PARKING_EXTRUDER)
  #endif
#endif
#if ANY(SWITCHING_TOOLHEAD, MAGNETIC_SWITCHING_TOOLHEAD, ELECTROMAGNETIC_SWITCHING_TOOLHEAD)
  #if ENABLED(SWITCHING_TOOLHEAD)
  #elif ENABLED(MAGNETIC_SWITCHING_TOOLHEAD)
    #if ENABLED(PRIME_BEFORE_REMOVE)
    #endif
  #elif ENABLED(ELECTROMAGNETIC_SWITCHING_TOOLHEAD)
  #endif
#endif
#if ENABLED(MIXING_EXTRUDER)
  #if ENABLED(GRADIENT_MIX)
  #endif
#endif
#if ENABLED(PSU_CONTROL)
  #if ENABLED(AUTO_POWER_CONTROL)
    #define AUTO_POWER_E_FANS
    #define AUTO_POWER_CONTROLLERFAN
    #define AUTO_POWER_CHAMBER_FAN
    #define AUTO_POWER_COOLER_FAN
  #endif
#endif
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_5 0
#define TEMP_SENSOR_6 0
#define TEMP_SENSOR_7 0
#define TEMP_SENSOR_BED 1
#define TEMP_SENSOR_PROBE 0
#define TEMP_SENSOR_CHAMBER 0
#define TEMP_SENSOR_COOLER 0
#define DUMMY_THERMISTOR_998_VALUE  25
#define DUMMY_THERMISTOR_999_VALUE 100
#define MAX_REDUNDANT_TEMP_SENSOR_DIFF 10
#define HEATER_0_MINTEMP   5
#define HEATER_1_MINTEMP   5
#define HEATER_2_MINTEMP   5
#define HEATER_3_MINTEMP   5
#define HEATER_4_MINTEMP   5
#define HEATER_5_MINTEMP   5
#define HEATER_6_MINTEMP   5
#define HEATER_7_MINTEMP   5
#define BED_MINTEMP        5
#define CHAMBER_MINTEMP    5
#define HEATER_0_MAXTEMP 275
#define HEATER_1_MAXTEMP 275
#define HEATER_2_MAXTEMP 275
#define HEATER_3_MAXTEMP 275
#define HEATER_4_MAXTEMP 275
#define HEATER_5_MAXTEMP 275
#define HEATER_6_MAXTEMP 275
#define HEATER_7_MAXTEMP 275
#define BED_MAXTEMP      125
#define CHAMBER_MAXTEMP  60
#define PIDTEMP
#if ENABLED(PIDTEMP)
  #if ENABLED(PID_PARAMS_PER_HOTEND)
    #define DEFAULT_Kp_LIST { 21.73, 21.73 }
    #define DEFAULT_Ki_LIST { 1.54, 1.54 }
    #define DEFAULT_Kd_LIST { 76.55, 76.55 }
  #else
    #define DEFAULT_Kp  22.20
    #define DEFAULT_Ki   1.08
    #define DEFAULT_Kd 114.00
  #endif
#if ENABLED(PIDTEMPBED)
  #define DEFAULT_bedKp 10.00
  #define DEFAULT_bedKi .023
  #define DEFAULT_bedKd 305.4
#if ENABLED(PIDTEMPCHAMBER)
  #define MIN_CHAMBER_POWER 0
  #define DEFAULT_chamberKp 37.04
  #define DEFAULT_chamberKi 1.40
  #define DEFAULT_chamberKd 655.17
#if ANY(PIDTEMP, PIDTEMPBED, PIDTEMPCHAMBER)
#endif
#define PREVENT_COLD_EXTRUSION
#define EXTRUDE_MINTEMP 170
#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MAXLENGTH 235
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
#endif
#if DISABLED(ENDSTOPPULLDOWNS)
#endif
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define E0_DRIVER_TYPE TMC2209
#define ENDSTOP_INTERRUPTS_FEATURE
#define DETECT_BROKEN_ENDSTOP
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 100.98 }
#define DEFAULT_MAX_FEEDRATE          { 500, 500, 20, 120 }
#if ENABLED(LIMITED_MAX_FR_EDITING)
#endif
#define DEFAULT_MAX_ACCELERATION      { 3000, 3000, 100, 10000 }
#if ENABLED(LIMITED_MAX_ACCEL_EDITING)
#endif
#define CLASSIC_JERK
#if ENABLED(CLASSIC_JERK)
  #define DEFAULT_XJERK 10.0
  #define DEFAULT_YJERK 10.0
  #define DEFAULT_ZJERK  0.3
  #if ENABLED(LIMITED_JERK_EDITING)
  #endif
#endif
#if DISABLED(CLASSIC_JERK)
#endif
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define BLTOUCH
#if ENABLED(TOUCH_MI_PROBE)
#endif
#if ENABLED(RACK_AND_PINION_PROBE)
  #define Z_PROBE_DEPLOY_X  X_MIN_POS
  #define Z_PROBE_RETRACT_X X_MAX_POS
#endif
#if ENABLED(DUET_SMART_EFFECTOR)
#endif
#define NOZZLE_TO_PROBE_OFFSET { -40, -12, 0 }
#define PROBING_MARGIN 15
#define XY_PROBE_FEEDRATE (100*60)
#define Z_PROBE_FEEDRATE_FAST (4*60)
#define Z_PROBE_FEEDRATE_SLOW (Z_PROBE_FEEDRATE_FAST / 2)
#if ENABLED(PROBE_ACTIVATION_SWITCH)
#endif
#if ENABLED(PROBE_TARE)
  #if ENABLED(PROBE_ACTIVATION_SWITCH)
  #endif
#endif
#define Z_PROBE_OFFSET_RANGE_MIN -20
#define Z_PROBE_OFFSET_RANGE_MAX 20
#define Z_MIN_PROBE_REPEATABILITY_TEST
#if ENABLED(PAUSE_BEFORE_DEPLOY_STOW)
#endif
#if ENABLED(PROBING_HEATERS_OFF)
#endif
#if ENABLED(PREHEAT_BEFORE_PROBING)
  #define PROBING_BED_TEMP     50
#endif
#define X_ENABLE_ON 0
#define Y_ENABLE_ON 0
#define Z_ENABLE_ON 0
#define DISABLE_X false
#define DISABLE_Y false
#define DISABLE_Z false
#define INVERT_X_DIR true
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false
#define INVERT_E0_DIR true
#define INVERT_E1_DIR false
#define INVERT_E2_DIR false
#define INVERT_E3_DIR false
#define INVERT_E4_DIR false
#define INVERT_E5_DIR false
#define INVERT_E6_DIR false
#define INVERT_E7_DIR false
#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1
#define X_BED_SIZE 235
#define Y_BED_SIZE 235
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 250
#define MIN_SOFTWARE_ENDSTOPS
#if ENABLED(MIN_SOFTWARE_ENDSTOPS)
  #define MIN_SOFTWARE_ENDSTOP_X
  #define MIN_SOFTWARE_ENDSTOP_Y
  #define MIN_SOFTWARE_ENDSTOP_Z
#endif
#define MAX_SOFTWARE_ENDSTOPS
#if ENABLED(MAX_SOFTWARE_ENDSTOPS)
  #define MAX_SOFTWARE_ENDSTOP_X
  #define MAX_SOFTWARE_ENDSTOP_Y
  #define MAX_SOFTWARE_ENDSTOP_Z
#endif
#if EITHER(MIN_SOFTWARE_ENDSTOPS, MAX_SOFTWARE_ENDSTOPS)
#endif
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FILAMENT_RUNOUT_SCRIPT "M600"
  #ifdef FILAMENT_RUNOUT_DISTANCE_MM
  #endif
#endif
#define AUTO_BED_LEVELING_BILINEAR
#define RESTORE_LEVELING_AFTER_G28
#if ENABLED(PREHEAT_BEFORE_LEVELING)
  #define LEVELING_BED_TEMP     50
#endif
#if ANY(MESH_BED_LEVELING, AUTO_BED_LEVELING_UBL, PROBE_MANUALLY)
#endif
#if ANY(MESH_BED_LEVELING, AUTO_BED_LEVELING_BILINEAR, AUTO_BED_LEVELING_UBL)
  #define ENABLE_LEVELING_FADE_HEIGHT
  #if ENABLED(ENABLE_LEVELING_FADE_HEIGHT)
  #endif
  #define SEGMENT_LEVELED_MOVES
  #if ENABLED(G26_MESH_VALIDATION)
  #endif
#endif
#if EITHER(AUTO_BED_LEVELING_LINEAR, AUTO_BED_LEVELING_BILINEAR)
  #define GRID_MAX_POINTS_X 3
  #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
  #if ENABLED(AAUTO_BED_LEVELING_BILINEARUTO_BED_LEVELING_BILINEAR)
    #if ENABLED(ABL_BILINEAR_SUBDIVISION)
      #define BILINEAR_SUBDIVISIONS 3
    #endif
  #endif
#elif ENABLED(AUTO_BED_LEVELING_UBL)
  #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
#elif ENABLED(MESH_BED_LEVELING)
  #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
#if ENABLED(LCD_BED_LEVELING)
#endif
#define LEVEL_BED_CORNERS
#if ENABLED(LEVEL_BED_CORNERS)
  #if ENABLED(LEVEL_CORNERS_USE_PROBE)
    #define LEVEL_CORNERS_PROBE_TOLERANCE 0.1
  #endif
  #define LEVEL_CORNERS_LEVELING_ORDER { LF, RF, RB, LB }
#endif
#define Z_SAFE_HOMING
#if ENABLED(Z_SAFE_HOMING)
#endif
#define HOMING_FEEDRATE_MM_M { (50*60), (50*60), (4*60) }
#define VALIDATE_HOMING_ENDSTOPS
#if ENABLED(SKEW_CORRECTION)
  #define XY_DIAG_AC 282.8427124746
  #define XY_DIAG_BD 282.8427124746
  #define XY_SIDE_AD 200
  #define XY_SKEW_FACTOR 0.0
  #if ENABLED(SKEW_CORRECTION_FOR_Z)
    #define XZ_DIAG_AC 282.8427124746
    #define XZ_DIAG_BD 282.8427124746
    #define YZ_DIAG_AC 282.8427124746
    #define YZ_DIAG_BD 282.8427124746
    #define YZ_SIDE_AD 200
    #define XZ_SKEW_FACTOR 0.0
    #define YZ_SKEW_FACTOR 0.0
  #endif
#endif
#if ENABLED(EEPROM_SETTINGS)
#endif
#define PREHEAT_1_LABEL       "PLA"
#define PREHEAT_1_TEMP_HOTEND 180
#define PREHEAT_1_TEMP_BED     70
#define PREHEAT_1_TEMP_CHAMBER 35
#define PREHEAT_2_LABEL       "ABS"
#define PREHEAT_2_TEMP_HOTEND 240
#define PREHEAT_2_TEMP_BED    110
#define PREHEAT_2_TEMP_CHAMBER 35
#define NOZZLE_PARK_FEATURE
#if ENABLED(NOZZLE_PARK_FEATURE)
  #define NOZZLE_PARK_POINT { (X_MIN_POS + 10), (Y_MAX_POS - 10), 20 }
#endif
#if ENABLED(NOZZLE_CLEAN_FEATURE)
  #define NOZZLE_CLEAN_STROKES  12
  #define NOZZLE_CLEAN_TRIANGLES  3
  #define NOZZLE_CLEAN_START_POINT { {  30, 30, (Z_MIN_POS + 1) } }
  #define NOZZLE_CLEAN_END_POINT   { { 100, 60, (Z_MIN_POS + 1) } }
  #define NOZZLE_CLEAN_CIRCLE_RADIUS 6.5
  #define NOZZLE_CLEAN_CIRCLE_FN 10
  #define NOZZLE_CLEAN_CIRCLE_MIDDLE NOZZLE_CLEAN_START_POINT
  #define NOZZLE_CLEAN_GOBACK
  #define NOZZLE_CLEAN_MIN_TEMP 170
#endif
#define PRINTJOB_TIMER_AUTOSTART
#if ENABLED(PRINTCOUNTER)
#endif
#if ENABLED(PASSWORD_FEATURE)
  #define PASSWORD_ON_STARTUP
#endif
#define LCD_LANGUAGE en
#define LCD_INFO_SCREEN_STYLE 0
#define SDSUPPORT
#define CR10_STOCKDISPLAY
#if ENABLED(SAV_3DGLCD)
  #define U8GLIB_SSD1306
#endif
#if ENABLED(DGUS_LCD_UI_MKS)
  #define USE_MKS_GREEN_UI
#endif
#if ENABLED(MALYAN_LCD)
#endif
#if EITHER(ANYCUBIC_LCD_I3MEGA, ANYCUBIC_LCD_CHIRON)
#endif
#if ENABLED(NEXTION_TFT)
#endif
#if ENABLED(EXTENSIBLE_UI)
#endif
#if ENABLED(TFT_GENERIC)
  #define TFT_DRIVER AUTO
#endif
#if ENABLED(TFT_LVGL_UI)
#endif
#if ENABLED(TOUCH_SCREEN)
  #define TOUCH_SCREEN_CALIBRATION
  #if BOTH(TOUCH_SCREEN_CALIBRATION, EEPROM_SETTINGS)
  #endif
  #if ENABLED(TFT_COLOR_UI)
  #endif
#endif
#define FAN_SOFT_PWM
#define SOFT_PWM_SCALE 0
#if EITHER(RGB_LED, RGBW_LED)
#endif
#if ENABLED(NEOPIXEL_LED)
  #if ENABLED(NEOPIXEL2_SEPARATE)
  #else
  #endif
#endif
#if ANY(BLINKM, RGB_LED, RGBW_LED, PCA9632, PCA9533, NEOPIXEL_LED)
  #define PRINTER_EVENT_LEDS
#endif
#define SERVO_DELAY { 300 }
