name: Firmware build

on:
  push:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out
      uses: actions/checkout@v2
    -
      name: Marlin auto build generation
      uses: thiago-scherrer/mabg@v1.4
    -
      name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware1.2
        path: .pio/build/STM32F103RC_btt_USB_maple/firmware.bin
