name: SKR Mini e3 v2.0 bltouch

on:
  push:
    branches: 2.0.x

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out
      uses: actions/checkout@v2
    -
      name: Marlin auto build generation
      uses: thiago-scherrer/mabg@v1.3
    -
      name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware2.0
        path: .pio/build/STM32F103RC_btt/firmware.bin
