name: Make firmware

on:
  push:
    branches: 2.0.x

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out
      uses: actions/checkout@v2
    -
      name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' 
        architecture: 'x64'
    -
      name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update
    -
      name: Build firmware
      run: |
        pio run
    -
      name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware1.2
        path: .pio/build/STM32F103RC_btt/firmware.bin
